title: "Muhammad Arham"
name: "Muhammad Arham"
description: "MS @ UAlberta | Reinforcement Learning | Machine Learning Engineer"
url: "https://muhammadarham-43.github.io"
baseurl: ""

paginate: 6
paginate_path: "/blog/page:num/"

include:
  - _pages

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"   # clean minimal theme
theme_skin_toggles: true
markdown: kramdown

author_profile: true
author:
  name: "Muhammad Arham"
  avatar: "/assets/images/profile-image.jpg"
  bio: "MS @ UAlberta · Reinforcement Learning · ML Engineer"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/arhamm40182"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/MuhammadArham-43"
    - label: "Google Scholar"
      icon: "fab fa-google-scholar"
      url: "https://scholar.google.com/citations?user=5c5ntW0AAAAJ&hl=en"
    - label: "X"
      icon: "fab fa-x-twitter"
      url: "https://x.com/arhamm40182"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:arhamm40182@gmail.com"
    - label: "Linktree"
      icon: "fas fa-link"
      url: "https://linktr.ee/muhammad.arham"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
