title: "Muhammad Arham"
name: "Muhammad Arham"
description: "MS @ UAlberta | Reinforcement Learning | Machine Learning Engineer"
url: "https://muhammadarham-43.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"   # clean minimal theme
markdown: kramdown

author:
  name: "Muhammad Arham"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I am a Machine Learning researcher, with experience in Computer Vision, Natural Language Processing (LLMs) and Reinforcement Learning"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/arhamm40182"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/MuhammadArham-43"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:arhamm40182@gmail.com"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
